In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
%matplotlib inline 

pd.set_option("display.max_columns",None)
pd.set_option("display.width",1000)

print("libraries imported.environement initialized")

libraries imported.environement initialized

In [3]:
dataset_path ="/kaggle/input/datasets/grandmaster07/student-exam-performance-dataset-analysis/StudentPerformanceFactors.csv"

df = pd.read_csv(dataset_path)

print ("first 5 sets of dataset")

display(df.head())

print("\n datasetshape rows and columns:")

print(df.shape)

print("\n column names:")

print(df. columns.tolist())

first 5 sets of dataset

   Hours_Studied  Attendance Parental_Involvement Access_to_Resources Extracurricular_Activities  Sleep_Hours  Previous_Scores Motivation_Level Internet_Access  Tutoring_Sessions Family_Income Teacher_Quality School_Type Peer_Influence  Physical_Activity Learning_Disabilities Parental_Education_Level Distance_from_Home  Gender  Exam_Score
0             23          84                  Low                High                         No            7               73              Low             Yes                  0           Low          Medium      Public       Positive                  3                    No              High School               Near    Male          67
1             19          64                  Low              Medium                         No            8               59              Low             Yes                  2        Medium          Medium      Public       Negative                  4                    No                  College           Moderate  Female          61
2             24          98               Medium              Medium                        Yes            7               91           Medium             Yes                  2        Medium          Medium      Public        Neutral                  4                    No             Postgraduate               Near    Male          74
3             29          89                  Low              Medium                        Yes            8               98           Medium             Yes                  1        Medium          Medium      Public       Negative                  4                    No              High School           Moderate    Male          71
4             19          92               Medium              Medium                        Yes            6               65           Medium             Yes                  3        Medium            High      Public        Neutral                  4                    No                  College               Near  Female          70

 datasetshape rows and columns:
(6607, 20)

 column names:
['Hours_Studied', 'Attendance', 'Parental_Involvement', 'Access_to_Resources', 'Extracurricular_Activities', 'Sleep_Hours', 'Previous_Scores', 'Motivation_Level', 'Internet_Access', 'Tutoring_Sessions', 'Family_Income', 'Teacher_Quality', 'School_Type', 'Peer_Influence', 'Physical_Activity', 'Learning_Disabilities', 'Parental_Education_Level', 'Distance_from_Home', 'Gender', 'Exam_Score']

In [4]:
print("dataset structural information:\n")

df.info()

print("printing a random sample from dataset")

display(df.sample(5))

dataset structural information:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   object
 3   Access_to_Resources         6607 non-null   object
 4   Extracurricular_Activities  6607 non-null   object
 5   Sleep_Hours                 6607 non-null   int64
 6   Previous_Scores             6607 non-null   int64
 7   Motivation_Level            6607 non-null   object
 8   Internet_Access             6607 non-null   object
 9   Tutoring_Sessions           6607 non-null   int64
 10  Family_Income               6607 non-null   object
 11  Teacher_Quality             6529 non-null   object
 12  School_Type                 6607 non-null   object
 13  Peer_Influence              6607 non-null   object
 14  Physical_Activity           6607 non-null   int64
 15  Learning_Disabilities       6607 non-null   object
 16  Parental_Education_Level    6517 non-null   object
 17  Distance_from_Home          6540 non-null   object
 18  Gender                      6607 non-null   object
 19  Exam_Score                  6607 non-null   int64
dtypes: int64(7), object(13)
memory usage: 1.0+ MB
printing a random sample from dataset

      Hours_Studied  Attendance Parental_Involvement Access_to_Resources Extracurricular_Activities  Sleep_Hours  Previous_Scores Motivation_Level Internet_Access  Tutoring_Sessions Family_Income Teacher_Quality School_Type Peer_Influence  Physical_Activity Learning_Disabilities Parental_Education_Level Distance_from_Home  Gender  Exam_Score
4562             15          85                 High              Medium                         No            7               82             High             Yes                  2        Medium          Medium      Public       Negative                  4                    No              High School                Far    Male          67
1403             24          71               Medium                High                        Yes            7               55              Low             Yes                  2          High          Medium      Public       Positive                  3                    No                  College                Far    Male          67
6339             20          97                  Low              Medium                        Yes            9               83             High             Yes                  3        Medium            High      Public       Positive                  3                    No             Postgraduate               Near  Female          73
5622             14          70               Medium              Medium                        Yes            9               51              Low             Yes                  1           Low            High      Public       Negative                  4                    No                  College               Near    Male          62
4847             17          88               Medium                High                        Yes           10              100           Medium             Yes                  1           Low            High      Public       Positive                  2                    No             Postgraduate               Near  Female          71

In [5]:
dataset_path_2 ="/kaggle/input/datasets/sammaw/energyconsumption/energy-consumption-by-source-and-country.csv"

df = pd.read_csv(dataset_path)

print ("first 5 sets of dataset")

display(df.head())

print("\n datasetshape rows and columns:")

print(df.shape)

print("\n column names:")

print(df. columns.tolist())

first 5 sets of dataset

   Hours_Studied  Attendance Parental_Involvement Access_to_Resources Extracurricular_Activities  Sleep_Hours  Previous_Scores Motivation_Level Internet_Access  Tutoring_Sessions Family_Income Teacher_Quality School_Type Peer_Influence  Physical_Activity Learning_Disabilities Parental_Education_Level Distance_from_Home  Gender  Exam_Score
0             23          84                  Low                High                         No            7               73              Low             Yes                  0           Low          Medium      Public       Positive                  3                    No              High School               Near    Male          67
1             19          64                  Low              Medium                         No            8               59              Low             Yes                  2        Medium          Medium      Public       Negative                  4                    No                  College           Moderate  Female          61
2             24          98               Medium              Medium                        Yes            7               91           Medium             Yes                  2        Medium          Medium      Public        Neutral                  4                    No             Postgraduate               Near    Male          74
3             29          89                  Low              Medium                        Yes            8               98           Medium             Yes                  1        Medium          Medium      Public       Negative                  4                    No              High School           Moderate    Male          71
4             19          92               Medium              Medium                        Yes            6               65           Medium             Yes                  3        Medium            High      Public        Neutral                  4                    No                  College               Near  Female          70

 datasetshape rows and columns:
(6607, 20)

 column names:
['Hours_Studied', 'Attendance', 'Parental_Involvement', 'Access_to_Resources', 'Extracurricular_Activities', 'Sleep_Hours', 'Previous_Scores', 'Motivation_Level', 'Internet_Access', 'Tutoring_Sessions', 'Family_Income', 'Teacher_Quality', 'School_Type', 'Peer_Influence', 'Physical_Activity', 'Learning_Disabilities', 'Parental_Education_Level', 'Distance_from_Home', 'Gender', 'Exam_Score']